daysUntilStale: 60
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - v2
  - needs-review
  - work-required
staleLabel: stale
markComment: >
  This issue has been automatically marked as stale because it hasn't seen
  a recent update. It'll be automatically closed in a few days.
closeComment: false
